Add  create new project
AgileVentures/WebsiteOne-FE pull request #142
Opened 2019-03-09 20:22 UTC by aonomike

- Add cypress tests for the create new project
- Add components for CreateProjectPage
- Add route for 'projects/new'

#### Issue addressed

fixes #139 

#### Screenshots (if appropriate):

#### Testing

2019-04-18 21:16 UTC, joaopapereira requested changes
Looks good, please review my comments

2019-04-18 21:16 UTC, joaopapereira commented on src/components/ProjectForm.js
> +    <Button type='submit' > Submit </Button> </Form >
What do you think we if we call this `Create Project`

2019-04-18 21:16 UTC, joaopapereira commented on src/tests/containers/CreateProjectPage.test.js
> +  // it('calls handleSubmit when the form is submitted', () => {
Why is this test commented out?

2019-04-20 01:00 UTC, mattwr18 commented on cypress/integration/common/web_steps.js
> +      .get('button[type=submit]')
sorry, I just noticed this @aonomike, why are we selecting the status? we aren't doing anything with it

2019-04-20 01:00 UTC, mattwr18 commented on cypress/integration/common/web_steps.js
> +    cy.window()
I think we want to change this cypress test to do what we are doing with the create events functionality in the React Mob.

You rightly brought up the bug that the way I had written the test was actually not testing that a user is being redirected by a successfully created event/project because I was, and you are, visiting the newlyCreatedProject.

2019-04-20 01:00 UTC, mattwr18 commented on src/reducers/createProjectReducer.js
> +  switch (action.type) {
As I brought up to you @aonomike, I am having doubts about what the point of saving the newlyCreatedProject/Event to the store when we are redirecting the user to the newlyCreatedProject/Event's info page where it reaches out to the backend to grab the project's/event's info. 

maybe it's a refactor? @joaopapereira what do you think? I can't think of any reason we need to have the user carry around the newlyCreatedProject/Event's info since the info they request from the backend on `componentDidMount` on the ProjectInfo.js/EventInfo.js includes all of the project's/event's info plus other info.

2019-04-20 01:00 UTC, mattwr18 commented on src/tests/actions/createProjectAction.test.js
> +    moxios.wait(() => {
really like that you had the idea to test for this, especially since we need to pass in a mock functionf for `history.push`, we might as well test that it's being called :smile_cat: 
good catch... need to create refactoring tickets to borrow your ideas :smile_cat:

2019-04-20 01:00 UTC, mattwr18 commented on src/tests/containers/CreateProjectPage.test.js
> +    history: { push: jest.fn() },
do we need this, or was this added when we were thinking of handling the redirection from the `CreateProjectPage.js`?

2019-04-22 17:36 UTC, aonomike commented on src/reducers/createProjectReducer.js
> +  switch (action.type) {
In the Stephen Grider course, he also does dispatch the response after create to store, maybe its just a convention? maybe there is something to it. Your thoughts @Kachulio1 @arku @FedericoEsparza @joaopapereira ?

2019-04-24 18:28 UTC, joaopapereira approved these changes

2019-04-24 18:31 UTC, merged