update the installation process
AgileVentures/WebsiteOne-FE pull request #153
Opened 2019-03-20 14:46 UTC by abdellani

#### Issue addressed

fixes #

#### Screenshots (if appropriate):

#### Testing

2019-03-20 18:39 UTC, joaopapereira requested changes
Can you please review my comment

2019-03-20 18:39 UTC, joaopapereira commented on README.MD
> -# Rebuild the semantic UI asserts
We are still using semantic UI, so I think we should keep this instructions here. Maybe add a disclaimer that this is only needed if we need to upgrade semantic

2019-03-22 10:18 UTC, abdellani commented
@joaopapereira 
I updated README.md as you suggested.

2019-03-23 14:13 UTC, mattwr18 commented
thanks @abdellani, sorry I didn't think about that use case @joaopapereira brought up

2019-03-25 18:04 UTC, joaopapereira approved these changes
Looks good, going to merge

2019-03-25 18:04 UTC, merged