Retyle homepage
AgileVentures/WebsiteOne-FE pull request #180
Opened 2019-04-09 09:49 UTC by Infinical

#### Issue addressed

fixes #

#### Screenshots (if appropriate):

#### Testing

2019-04-09 12:04 UTC, mattwr18 commented
Could you please upload some screen shots @Infinical

2019-04-09 14:07 UTC, Infinical commented
![Screenshot at 2019-04-09 17-05-55](https://user-images.githubusercontent.com/16985576/55806902-dfcacb00-5ae9-11e9-8de6-193546d60ee1.png)
![Screenshot at 2019-04-09 17-05-37](https://user-images.githubusercontent.com/16985576/55806903-dfcacb00-5ae9-11e9-9156-cad69c21fd9e.png)
![Screenshot at 2019-04-09 17-05-13](https://user-images.githubusercontent.com/16985576/55806904-e0636180-5ae9-11e9-9c7e-35720decacd3.png)

2019-04-09 14:59 UTC, mattwr18 commented
great! thanks @Infinical 
will you be able join the #anvil meeting today?

Going back to what you were asking, I think it will definitely be better to separate the Modals, if possible.
Then as you said we can maybe style them similarly to how they are in production or maybe even a better design?

Also, it would be great if you could find a way to add some padding on the left of the images, and maybe change the transparency of the background image?

2019-04-09 17:20 UTC, joaopapereira requested changes
Please review my comments

2019-04-09 17:20 UTC, joaopapereira commented on src/components/homepage/HomepageModal.scss
> +
```suggestion
```

2019-04-09 17:20 UTC, joaopapereira commented on src/components/homepage/Homepage.css
> +  background-image: url("../../images/landing-page-background.png") !important;
Do we need the important?

2019-04-09 17:27 UTC, mattwr18 requested changes

2019-04-09 17:27 UTC, mattwr18 commented on src/components/homepage/HomepageModal.scss
> +  opacity: 30%;
it looks like we can add `padding-left` here

2019-04-25 14:01 UTC, mattwr18 commented
@Infinical I'm gonna close this as I put in a separate `PR` that was merged in building off of yours and @Kachulio1's work

2019-04-25 14:01 UTC, closed without merging