Hiding members and issue tracker cards when no data is present
AgileVentures/WebsiteOne-FE pull request #197
Opened 2019-04-19 01:30 UTC by jmpainter

- ProjectSummary.js - adding conditional rendering for members and issue tracker cards if not data is present

If this looks ok, I can add tests to ProjectSummary.test.js

2019-04-22 15:38 UTC, mattwr18 commented
@jmpainter it is failing the build on `standard` errors, can you please run `yarn fix` and push it back up?

2019-04-23 01:49 UTC, jmpainter commented
I ran yarn fix and pushed it up. Will make sure to do in the future.

2019-04-23 19:42 UTC, jmpainter commented
I added tests in ProjectSummary.test.js

2019-04-24 19:41 UTC, joaopapereira requested changes
LGTM, please just remove the console log and we should be fine to merge it

2019-04-24 19:41 UTC, joaopapereira commented on src/components/ProjectSummary.js
> +  console.log(project)
we should remove this console log

2019-04-24 19:41 UTC, joaopapereira commented on src/components/ProjectSummary.js
> +                {(project.pivotaltracker_url || project.sourceRepositories.length > 0 || project.slack_channel_name) ? (
it is starting to look like a new component is needed here to make it more readable. Nevertheless I am ok merging it like this and refactor it later

2019-04-24 20:26 UTC, jmpainter commented
I removed the console.log from ProjectSummary.js

2019-04-25 17:25 UTC, mattwr18 commented
great job @jmpainter!!

2019-04-26 15:39 UTC, joaopapereira approved these changes
LGTM

2019-04-26 15:40 UTC, merged