added repos and trackers to ProjectForm
AgileVentures/WebsiteOne-FE pull request #219
Opened 2019-05-01 18:35 UTC by jmpainter

I found the cleanest implementation to be the use of redux-forms's FieldArray component.
The unit tests are passing, but I wanted to see what was thought about tests for the custom FieldArray component and the integration test for the ProjectForm

new file:   src/assets/CreateProjectPage.css - some styling needed for form additions
new file:   src/components/FieldGroup.js - custom redux-form FieldArray component
modified:   src/components/ProjectForm.js - added two redux-form FieldArray  components for repos and trackers
new file:   src/helpers/validators.js - validation for ProjectForm

fixes #203

2019-05-04 13:32 UTC, mattwr18 requested changes
This is really great work @jmpainter!! 
I made some comments and suggestions, please feel free to let me know if there were motives I don't understand behind making the decisions you made, and/or push back on any changes you think are better not made. 

Also, it would be really helpful if you could get in the habit of uploading screenshots so that reviewers or just people interested in checking out what it looks like could do so without needing to pull down the branch and run the server/interact with the form.

Really impressed by how thorough you are on your `PR`s!!

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/FieldGroup.test.js
> +    }).length).toEqual(1)
with Jest you can use `toHaveLength(1)` https://jestjs.io/docs/en/expect#tohavelengthnumber

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/FieldGroup.test.js
> +  it('creates an add button with the correct type', () => {
should this test be moved before the one starting on line 64?

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/FieldGroup.test.js
> +  it('adds a field', () => {
does it make sense to say `supports field addition` or something similar that portrays the idea that the user triggers the action?

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/FieldGroup.test.js
> +  it('removes a field', () => {
same as above :point_up:

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/ProjectForm.test.js
> +  it('adds new repo fields', () => {
same as above :point_up:

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/ProjectForm.test.js
> +    expect(wrapper.find('Field[name="repos[0].value"]').length).toBeTruthy()
I am not a fan of `.toBeTruthy()` tests cause I feel like they are flaky... is there a way that you can test this without using it? 
here is something on the subject, if you want to have a look https://stackoverflow.com/questions/32615713/tobetrue-vs-tobetruthy-vs-tobetrue

I know there is `exists()` https://airbnb.io/enzyme/docs/api/ReactWrapper/exists.html... 
I'm assuming it doesn't have a predetermined length that we could use `toHaveLength(n)`?

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/ProjectForm.test.js
> +    expect(wrapper.find('Field[name="repos[1].value"]').length).toBeTruthy()
can we avoid using multiple `expects` in the same it block?
https://softwareengineering.stackexchange.com/questions/7823/is-it-ok-to-have-multiple-asserts-in-a-single-unit-test

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/ProjectForm.test.js
> +    console.log(wrapper.debug())
just to point it out, cause everyone misses them sometimes :stuck_out_tongue:

2019-05-04 13:32 UTC, mattwr18 commented on src/tests/components/ProjectForm.test.js
> +    console.log(wrapper.debug())
another one... they're sneaky :rofl:

2019-05-04 18:17 UTC, jmpainter commented
Thanks for the suggestions. I've made these updates and added one more test to FieldGroup.

2019-05-07 16:55 UTC, joaopapereira approved these changes
LGTM

2019-05-07 18:23 UTC, mattwr18 commented
hey @jmpainter, I know I mentioned this is another `PR` review, but I'm not sure if you saw it. 
could you upload screen shots? it helps for us to give quicker feedback.

I think the code looks good, thank you for making the requested changes. :smile_cat: 
a couple things I noticed having pulled it down
![Screenshot at 2019-05-07 15:15:28](https://user-images.githubusercontent.com/26943915/57323005-489e6680-70db-11e9-9031-7eb17c8a3d74.png)

Is there any way we can have the fields added between the `Delete` button and the `Add` button? like 
![Screenshot at 2019-05-07 15:20:10](https://user-images.githubusercontent.com/26943915/57323165-a468ef80-70db-11e9-8c20-1b490d8d1749.png)

Also, I think we want to avoid just grey buttons, maybe we could make the `Remove` like https://react.semantic-ui.com/elements/button/#variations-negative
and the `Add` the `#34495E` blue color? what do you think? or if people think it looks better, maybe it could stay grey, but would look better with the `negative` color contrast?

2019-05-07 21:30 UTC, jmpainter commented
I changed the placement of the add buttons and the colors of the add and remove buttons. I used the 'negative' class on the remove button. For the add buttons, the prop color="blue" was added. This looked like the way most native to React Semantic UI.
![FieldGroup](https://user-images.githubusercontent.com/10214686/57334435-982d6400-70d4-11e9-8611-7e8bcb3788c3.png)

2019-05-07 23:52 UTC, mattwr18 approved these changes
Great! looks good @jmpainter 
maybe we can open a separate ticket to move the `Create Project` button to the right so it's not directly below the others.
and is it just me or is the orange from our logo a little too similar to `negative` color from semantic ui react?
maybe we could consider changing it to the blue color from the navbar and footer?
separate ticket, though... as long as @joaopapereira is happy, let's get this merged!!

2019-05-08 17:32 UTC, jmpainter commented
Ok, sounds good.

2019-05-08 21:48 UTC, merged