204 add slack channel name on create new project form
AgileVentures/WebsiteOne-FE pull request #221
Opened 2019-05-02 07:50 UTC by chris110408

Issue addressed
Add form field to add slack channel name on Create New Project form issue 204

fixes #
Expected Behavior
Add Form input field to add slack_channel_name
Add a label next to the Input field displaying slack_channel_name
Current Behavior
There is no form input field for slack channel name.

Possible Solution
Add Semantic UI react Form.Input to add Input to add field to the form

test:
the original unit test for action has problem use the newproject data to compare with newproject and always show success.

2019-05-07 17:02 UTC, joaopapereira requested changes
Great contribution. Looks good, but please review my comments

2019-05-07 17:02 UTC, joaopapereira commented on src/tests/actions/createProjectAction.test.js
> +describe.only('createProject', () => {
```suggestion
describe('createProject', () => {
```

2019-05-07 17:02 UTC, joaopapereira commented on src/tests/actions/createProjectAction.test.js
> +  it.only('posts project info to Rails backend and returns without error', async () => {
```suggestion
  it('posts project info to Rails backend and returns without error', async () => {
```

2019-05-07 17:02 UTC, joaopapereira commented on src/tests/components/ProjectForm.test.js
> +describe.only('ProjectForm', () => {
```suggestion
describe('ProjectForm', () => {
```

2019-05-07 17:02 UTC, joaopapereira commented on src/tests/components/ProjectForm.test.js
> +    console.log(ProjectForm)
```suggestion
```

2019-05-21 15:28 UTC, mattwr18 commented
closed in favor of https://github.com/AgileVentures/WebsiteOne-FE/pull/243, which was also put in by @chris110408

2019-05-21 15:28 UTC, closed without merging