[WIP ] #151 Edit events
AgileVentures/WebsiteOne-FE pull request #242
Opened 2019-05-15 01:28 UTC by abdellani

#### Issue addressed

https://github.com/AgileVentures/WebsiteOne-FE/issues/151

#### Screenshots (if appropriate):

#### Testing

2019-05-15 01:46 UTC, abdellani commented
@mattwr18 
At this level, users have access to the edit event form with data preloaded. Now, I wonder how to implement the change handlers for the form? is it better to do the changes at the component's state  or do I need to use actions/store  ?

2019-05-21 11:41 UTC, mattwr18 commented
hey @abdellani there are 4 jest tests that are failing on the build, are they failing in the same way locally?

2019-05-22 11:22 UTC, abdellani commented
@mattwr18 
Is `/api/v1/events/${slug}` supposed to send data structured in the same way like in [cypress/fixtures/event.json](https://github.com/AgileVentures/WebsiteOne-FE/blob/develop/cypress/fixtures/event.json)  ? 
I'm asking because I faced a problem while writing cypress test. When I try to edit the event,  [src/actions/getEventInfoAction.js](https://github.com/AgileVentures/WebsiteOne-FE/blob/develop/src/actions/getEventInfoAction.js), The summary page doesn't show all the details, like the name for example.

2019-05-24 11:04 UTC, mattwr18 requested changes

2019-05-24 11:04 UTC, mattwr18 commented on src/actions/updateEventAction.js
> +      history.push(`/events/${response.data.event.slug}`)
We were talking about this is in the meeting @abdellani 
@joaopapereira has requested that we extract this concern from the action into either the reducer or the container...
so far we have other examples, i.e `Login.js`, where it is the concern of the container
Maybe, though we just want to open a ticket and do them all at the same time?

2019-05-24 11:04 UTC, mattwr18 commented on src/containers/EditEventPage.js
> +      this.props.fetchEventInfo(this.props.match.params.slug)
it seems a bit strange to have a `fetchEventInfo` nested inside an if block checking about the length of the projects array, doesn't it? I think I left it there in our pairing session?

2019-05-24 11:04 UTC, mattwr18 commented on src/containers/EditEventPage.js
> +// )(EditEventPage)
please remove the comments :smile_cat:

2019-05-25 13:21 UTC, mattwr18 commented
this is great @abdellani, I think we can get this merged soon... I'll pull down the latest changes and check it out.. did you see why the test coverage dropped?

2019-05-28 02:07 UTC, mattwr18 requested changes

2019-05-28 02:07 UTC, mattwr18 commented on src/containers/EditEventPage.js
> +            Creating a new Event
should this be `Editing Event`, or something similar @abdellani?

2019-06-27 19:19 UTC, aonomike commented
I think the test coverage dropped since there are no tests for `updateEventsAction.js`. Maybe an update to that would improve the coverage @abdellani @mattwr18  ?

2022-11-19 06:24 UTC, closed without merging