21 signup page
AgileVentures/WebsiteOne-FE pull request #38
Opened 2019-01-15 21:20 UTC by mattwr18

#### Issue addressed

fixes #21 

#### Screenshots (if appropriate):

![screenshot at 2019-01-15 19 19 37](https://user-images.githubusercontent.com/26943915/51210675-8bed8300-18fa-11e9-97e7-7a245bf2b872.png)

#### Testing

no integration tests, but the coverage is quite high

2019-01-15 21:22 UTC, mattwr18 commented
getting this type of output on circleci
```
Unarchiving cache...
tar: root/WebsiteOne-FE/node_modules: Cannot mkdir: Permission denied
tar: root/WebsiteOne-FE/node_modules/.bin: Cannot mkdir: Permission denied
tar: root/WebsiteOne-FE/node_modules/.bin/JSONStream: Cannot open: Permission denied
tar: root/WebsiteOne-FE/node_modules/.bin/acorn: Cannot open: Permission denied
tar: root/WebsiteOne-FE/node_modules/.bin/ansi-html: Cannot open: Permission denied
tar: root/WebsiteOne-FE/node_modules/.bin/atob: Cannot open: Permission denied
```
it's passing on travis though

2019-01-16 03:54 UTC, joaopapereira requested changes
Good job on sign up. I do have some questions and comment, please review them

2019-01-16 03:54 UTC, joaopapereira commented on src/containers/SignUp.js
> +          message: 'Have a look around',
Message is not same as in story

2019-01-16 03:54 UTC, joaopapereira commented on src/tests/containers/SignUp.test.js
> +    const mainHeader = wrapper.find('Header').filterWhere(item => {
Not sure about the value of the test

2019-01-16 03:54 UTC, joaopapereira commented on src/tests/containers/SignUp.test.js
> +  it('should have a Form', () => {
Not sure about the value of the test

2019-01-16 03:54 UTC, joaopapereira commented on src/tests/containers/SignUp.test.js
> +  it('should update the state when email input value changes', () => {
Not sure about the value of the test

2019-01-16 03:54 UTC, joaopapereira commented on src/tests/containers/SignUp.test.js
> +  it('should update the state when password input value changes', () => {
Not sure about the value of the test

2019-01-16 03:54 UTC, joaopapereira commented on src/tests/containers/SignUp.test.js
> +  it('should call handleSignUp and postSignUpInfo when the form is submitted', async () => {
Missing the failure case

2019-01-16 03:54 UTC, joaopapereira commented on src/tests/reducers/usersReducer.test.js
> +  expect(
Maybe it would be it a separate it block

2019-01-21 15:54 UTC, joaopapereira approved these changes
Looks good, going to merge

2019-01-21 15:54 UTC, merged